name: Build APK

on:
  push:
    branches:
      - master  # замени на main, если твоя ветка называется main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^# *source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/^# *log_level = .*/log_level = 2/' buildozer.spec
          sed -i 's/^# *android.permissions = .*/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/^# *package.name = .*/package.name = CaRT/' buildozer.spec
          sed -i 's/^# *package.domain = .*/package.domain = org.example.cart/' buildozer.spec
          echo "requirements = python3,kivy,kivymd" >> buildozer.spec
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: CaRT-debug.apk
          path: bin/*.apk
