name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk wget
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"

          cd "$HOME/android-sdk"
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools-temp
          rm cmdline-tools.zip

          mkdir -p "$HOME/android-sdk/cmdline-tools/latest"
          mv cmdline-tools-temp/cmdline-tools/* "$HOME/android-sdk/cmdline-tools/latest"
          rm -rf cmdline-tools-temp

          export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
          yes | "$HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$HOME/android-sdk" \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;34.0.0"

      - name: 🔧 Fix sdkmanager path for Buildozer
        run: |
          mkdir -p "$HOME/android-sdk/tools"
          ln -s "$HOME/android-sdk/cmdline-tools/latest" "$HOME/android-sdk/tools/bin"

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/tools/bin" >> $GITHUB_ENV

      - name: Link SDK to Buildozer expected path
        run: |
          mkdir -p ~/.buildozer/android/platform
          ln -sfn $HOME/android-sdk ~/.buildozer/android/platform/android-sdk

      - name: Build APK
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

          sed -i 's/^# *source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/^# *log_level = .*/log_level = 2/' buildozer.spec
          sed -i 's/^# *android.permissions = .*/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/^# *package.name = .*/package.name = CaRT/' buildozer.spec
          sed -i 's/^# *package.domain = .*/package.domain = org.example.cart/' buildozer.spec
          sed -i '/^requirements =/d' buildozer.spec
          echo "requirements = python3,kivy,kivymd" >> buildozer.spec

          buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CaRT-debug.apk
          path: bin/*.apk
